[package]
name = "constants"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]


[features]
default = ["tiny"]
tiny = []
full = []