[package]
name = "disputes"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
jam-types = { workspace = true }
block = { workspace = true }