[package]
name = "vinwolf"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ark-ec-vrfs ={ git = "https://github.com/davxy/ark-ec-vrfs", rev = "ea35e224f79c6f920e3816ae2e3cfdb02e2e8448", features = ["bandersnatch", "ring", "parallel"] }
hex = "0.4.3"
frame-support = "37.0.0"
sp-core = "34.0.0"
array-bytes = "6.2.3"
num = "0.4"
erasure-coding = { git = "https://github.com/paritytech/erasure-coding.git", branch = "main" }
once_cell = "1.17"

[dev-dependencies]
quickcheck = { version = "1.0.3", default-features = false }