[package]
name = "database"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
rocksdb = { workspace = true }
hex = { workspace = true }
thiserror = "1"