[package]
name = "node"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
bandersnatch-vrf-spec = { workspace = true }
block = { workspace = true }
codec = { workspace = true }
constants = { workspace = true }
jam-types = { workspace = true }
network = { path = "../network" }
quinn = { workspace = true }
rustls = { version = "0.23.31", features = ["ring"] }
safrole = { workspace = true }
state-handler = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tools = { workspace = true }

[features]
default = ["tiny"]
full = ["constants/full", "network/full"]
tiny = ["constants/tiny", "network/tiny"]
DB = ["network/DB"]
